# fly.toml

app = "transactionaggregationapi"
primary_region = "jnb"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "pshongwe/transactionaggregationapi:latest"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  DOTNET_RUNNING_IN_CONTAINER = "true"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.health_checks]
    [services.health_checks.http]
      path = "/health"
      interval = "10s"
      timeout = "2s"
      grace_period = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"